version: '2'

networks:
  elasticsearch-fluentd:
    driver: bridge
  elasticsearch-logstash:
    driver: bridge
  elasticsearch-kibana:
    driver: bridge
  elasticsearch-cluster:
    driver: bridge
  

services:
  gateway:
    restart: unless-stopped
    image: itzg/elasticsearch
    cap_add:
      - IPC_LOCK
    networks:
      - elasticsearch-fluentd
      - elasticsearch-logstash
      - elasticsearch-kibana
      - elasticsearch-cluster
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - /opt/vm-data/elasticsearch-gateway/data:/data
    environment:
      UNICAST_HOSTS: master
      TYPE: GATEWAY
      ES_JAVA_OPTS: "-Xms1g -Xmx2g"

  master:
    restart: unless-stopped
    image: itzg/elasticsearch
    cap_add:
      - IPC_LOCK
    networks:
      - elasticsearch-cluster
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - /opt/vm-data/elasticsearch-master/data:/data
    environment:
      UNICAST_HOSTS: gateway
      TYPE: MASTER
      MIN_MASTERS: 2
      ES_JAVA_OPTS: "-Xms1g -Xmx2g"

  data:
    restart: unless-stopped
    image: itzg/elasticsearch
    cap_add:
      - IPC_LOCK
    networks:
      - elasticsearch-cluster
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - /opt/vm-data/elasticsearch-data/data:/data
    environment:
      UNICAST_HOSTS: master,gateway
      TYPE: DATA
      ES_JAVA_OPTS: "-Xms1g -Xmx2g"


  fluentd:
    restart: unless-stopped
    build: fluentd/
    container_name: fluentd
    depends_on:
      - elasticsearch1
      - elasticsearch2
    networks:
      - elasticsearch-fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./fluentd/conf:/fluentd/etc


  logstash:
    restart: unless-stopped
    build: logstash/
    container_name: logstash
    depends_on:
      - elasticsearch1
      - elasticsearch2
    networks:
      - elasticsearch-logstash
    ports:
      - 5000:5000/udp
      - 25826:25826 # syslog port
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    environment:
      - LS_HEAP_SIZE=1024m

  kibana:
    restart: unless-stopped
    build: kibana/
    container_name: kibana
    depends_on:
      - elasticsearch1
      - elasticsearch2
    networks:
      - elasticsearch-kibana
    ports:
      - 5601:5601
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
