version: '2'

networks:
  elasticsearch-fluentd:
    driver: bridge
  elasticsearch-logstash:
    driver: bridge
  elasticsearch-kibana:
    driver: bridge
  elasticsearch-cluster:
    driver: bridge
  

services:

  elasticsearch1:
    restart: unless-stopped
    build: elasticsearch/
    container_name: elasticsearch1
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    # mem_limit: 1g
    networks:
      - elasticsearch-fluentd
      - elasticsearch-logstash
      - elasticsearch-kibana
      - elasticsearch-cluster
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - /opt/vm-data/elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      # disable X-Pack
      # see https://www.elastic.co/guide/en/x-pack/current/xpack-settings.html
      #     https://www.elastic.co/guide/en/x-pack/current/installing-xpack.html#xpack-enabling
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false

  elasticsearch2:
    restart: unless-stopped
    build: elasticsearch/
    container_name: elasticsearch2
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    # mem_limit: 1g
    networks:
      - elasticsearch-cluster
    volumes:
      - /opt/vm-data/elasticsearch2/data:/usr/share/elasticsearch/data
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "discovery.zen.ping.unicast.hosts=elasticsearch1"
      # disable X-Pack
      # see https://www.elastic.co/guide/en/x-pack/current/xpack-settings.html
      #     https://www.elastic.co/guide/en/x-pack/current/installing-xpack.html#xpack-enabling
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false

  fluentd:
    restart: unless-stopped
    build: fluentd/
    container_name: fluentd
    depends_on:
      - elasticsearch1
      - elasticsearch2
    networks:
      - elasticsearch-fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./fluentd/conf:/fluentd/etc


  logstash:
    restart: unless-stopped
    build: logstash/
    container_name: logstash
    depends_on:
      - elasticsearch1
      - elasticsearch2
    networks:
      - elasticsearch-logstash
    ports:
      - 5000:5000/udp
      - 25826:25826 # syslog port
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    environment:
      - LS_HEAP_SIZE=1024m

  kibana:
    restart: unless-stopped
    build: kibana/
    container_name: kibana
    depends_on:
      - elasticsearch1
      - elasticsearch2
    networks:
      - elasticsearch-kibana
    ports:
      - 5601:5601
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
