version: '2'

networks:
  elasticsearch:
    driver: bridge
  

services:

  master:
    restart: unless-stopped
    image: itzg/elasticsearch
    networks:
      - elasticsearch
    volumes:
      - /opt/vm-data/elasticsearch-master/data:/data
    environment:
      TYPE: MASTER
      UNICAST_HOSTS: master
      MIN_MASTERS: 1
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"

  data:
    restart: unless-stopped
    image: itzg/elasticsearch
    networks:
      - elasticsearch
    volumes:
      - /opt/vm-data/elasticsearch-data/data:/data
    environment:
      TYPE: DATA
      UNICAST_HOSTS: master
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"

  gateway:
    restart: unless-stopped
    image: itzg/elasticsearch
    networks:
      - elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - /opt/vm-data/elasticsearch-gateway/data:/data
    environment:
      TYPE: GATEWAY
      UNICAST_HOSTS: master
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"

  ingest:
    restart: unless-stopped
    image: itzg/elasticsearch
    networks:
      - elasticsearch
    ports:
      - "9222:9200"
    volumes:
      - /opt/vm-data/elasticsearch-ingest/data:/data
    environment:
      TYPE: INGEST
      UNICAST_HOSTS: master
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"

  fluentd:
    restart: unless-stopped
    build: fluentd/
    container_name: fluentd
    depends_on:
      - gateway
      - master
      - data
      - ingest
    networks:
      - elasticsearch
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./fluentd/conf:/fluentd/etc


  logstash:
    restart: unless-stopped
    build: tenstartups/logstash
    container_name: logstash
    depends_on:
      - gateway
      - master
      - data
      - ingest
    networks:
      - elasticsearch
    ports:
      - 25826:25826 # syslog port
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"

  kibana:
    restart: unless-stopped
    build: kibana/
    container_name: kibana
    depends_on:
      - gateway
      - master
      - data
      - ingest
    networks:
      - elasticsearch
    ports:
      - 5601:5601
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
